const DISCORD='https://discord.gg/rdV2qfe3ua';
const games=[
 {name:'Anime Ascend',genre:'Anime Simulator',status:'In Development',img:'assets/games/anime-ascend.webp',desc:'Grow stronger, break through barriers, and unlock new worlds.',href:DISCORD}
];
const team=[
 {name:'Asgard',role:'Owner',group:'Executive',img:'assets/team/asgard.webp',discord:'https://discord.com/users/1187421394695376968',bio:'Studio owner and executive lead defining the vision and direction of Solara Inc.'},
 {name:'Diego',role:'Co-Owner · Scripter',group:'Executive',img:'assets/team/diego.webp',discord:'https://discord.com/users/1248575202946846755',bio:'Co-leads the studio while building gameplay systems and technical foundations.'},
 {name:'Kzyh',role:'Leader Manager',group:'Leadership',img:'assets/team/kzyh.webp',discord:'https://discord.com/users/1360958504063471747',bio:'Leads management, team organization and project coordination.'},
 {name:'Guga',role:'Programmer',group:'Engineering',img:'assets/team/guga.webp',discord:'https://discord.com/users/738811406501281844',bio:'Develops systems and technical features behind our experiences.'},
 {name:'Shinzaki',role:'UI/UX Maker',group:'Design',img:'assets/team/shinzaki.webp',discord:'https://discord.com/users/1475261480495611956',bio:'Shapes clear, distinctive interfaces and player experiences.'},
 {name:'Sanny',role:'VFX Maker',group:'Creative',img:'assets/team/sanny.webp',discord:'https://discord.com/users/1537203659580907631',bio:'Creates visual effects for abilities, attacks and impactful moments.'},
 {name:'Susu',role:'Modeler',group:'Creative',img:'assets/team/susu.webp',discord:'https://discord.com/users/1181353153082433638',bio:'Builds optimized 3D assets aligned with each project’s art direction.'},
 {name:'Osnofa',role:'Builder',group:'Creative',img:'assets/team/osnofa.webp',discord:'https://discord.com/users/1413268553620000950',bio:'Creates worlds, environments and playable spaces.'},
 {name:'Meg',role:'Animator',group:'Creative',img:'assets/team/meg.webp',discord:'https://discord.com/users/867405277569613894',bio:'Brings characters and gameplay moments to life through animation.'}
];
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function nav(){const p=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.links a[data-page]').forEach(a=>a.dataset.page===p&&a.classList.add('active'));document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('.nav').classList.toggle('open'))}
function gameCard(g){return `<article class="gameCard reveal"><a class="gameVisual imageVisual" href="${g.href}" target="_blank" rel="noopener"><img src="${g.img}" alt="${esc(g.name)}" loading="lazy" decoding="async"><span class="gameStatus"><i></i>${esc(g.status)}</span><span class="openIcon gameOpen">↗</span></a><div class="cardBody"><div class="micro">${esc(g.genre)}</div><h3>${esc(g.name)}</h3><p>${esc(g.desc)}</p><div class="cardFoot"><span>Solara Inc · Project 01</span><a href="${g.href}" target="_blank" rel="noopener">Join Discord ↗</a></div></div></article>`}
function memberCard(m,featured=false){return `<article class="memberCard reveal ${featured?'featured':''}"><a class="memberMedia" href="${m.discord}" target="_blank" rel="noopener" aria-label="Open ${esc(m.name)} on Discord"><img src="${m.img}" alt="${esc(m.name)}" loading="lazy" decoding="async"><span class="roleBadge">${esc(m.role)}</span><span class="openIcon">↗</span></a><div class="memberInfo"><div><div class="micro">${esc(m.group)}</div><h3>${esc(m.name)}</h3></div><p>${esc(m.bio)}</p><a class="discordLink" href="${m.discord}" target="_blank" rel="noopener">Discord profile ↗</a></div></article>`}
function render(){const fg=document.querySelector('#featuredGames');if(fg)fg.innerHTML=games.map(gameCard).join('');const ow=document.querySelector('#owners');if(ow)ow.innerHTML=team.filter(x=>x.group==='Executive').map(x=>memberCard(x,true)).join('');const ag=document.querySelector('#allGames');if(ag)ag.innerHTML=games.map(gameCard).join('');const tg=document.querySelector('#teamGroups');if(tg){const groups=[['Executive','Studio Direction'],['Leadership','Management'],['Engineering','Code & Systems'],['Design','Product Experience'],['Creative','Art & World']];tg.innerHTML=groups.map(([gr,label],i)=>{const people=team.filter(x=>x.group===gr);return people.length?`<section class="teamGroup"><div class="teamGroupHeader reveal"><div><div class="micro">0${i+1} / ${label}</div><h2>${gr}</h2></div><span>${people.length} ${people.length===1?'member':'members'}</span></div><div class="teamGrid">${people.map(x=>memberCard(x,gr==='Executive')).join('')}</div></section>`:''}).join('')}}
function reveal(){if(matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.reveal').forEach(x=>x.classList.add('show'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{rootMargin:'0px 0px -8%'});document.querySelectorAll('.reveal').forEach(x=>io.observe(x))}
document.addEventListener('DOMContentLoaded',()=>{render();nav();requestAnimationFrame(reveal)});
